### ISSUE TITLE
onColorChange prop not called after press the slider (without gesture).

### ISSUE THREAD

**Issue by kumkao** [flyskywhy/react-native-slider-color-picker#1]
Hello,
I used <SliderHuePicker> component. I found that the component not update the color value if I press the slider instead of gesture.
I think you could add the onSlidingStart prop to <Slider> to handle the changes.

**Comment by flyskywhy** [comment]
Maybe it's related to https://github.com/software-mansion/react-native-gesture-handler/issues/984#issuecomment-619664158

You can try set `useNativeDrive` to false in react-native-smooth-slider/src/Slider.js
