### ISSUE TITLE
Slider doesn't work on android.

### ISSUE THREAD

**Issue by CozmaCatalin** [flyskywhy/react-native-slider-color-picker#2]
On iOS there is no problem , but on android , the slider doesn't work.
Anyone have this problem ?

**Comment by flyskywhy** [comment]
1. As README.md described "some Android phone PanGestureHandler causes Animated Value to jump when using native driver" , then you need `useNativeDriver={false}`
2. If you use react-native-slider-color-picker in a modal, maybe you need this https://github.com/software-mansion/react-native-gesture-handler/issues/139#issuecomment-722062723

**Comment by CozmaCatalin** [comment]
> 1. As README.md described "some Android phone PanGestureHandler causes Animated Value to jump when using native driver" , then you need `useNativeDriver={false}`
> 2. If you use react-native-slider-color-picker in a modal, maybe you need this [software-mansion/react-native-gesture-handler#139 (comment)](https://github.com/software-mansion/react-native-gesture-handler/issues/139#issuecomment-722062723)

**Comment by MriduDixit15** [comment]
added useNativeDriver={false} on SliderValuePicker , but not working properly on android,

**Comment by flyskywhy** [comment]
What's your RN and react-native-gesture-handler version?

MriduDixit15 ***@***.***> 于2021年5月24日周一 下午7:54写道：

**Comment by MriduDixit15** [comment]
i faced prob in Emulator,in real device working fine . so no issue .thankyou

**Comment by flyskywhy** [comment]
`@flyskywhy/react-native-modal-animated` perform a workaround for react-native-gesture-handler [Doesn't work in a modal](https://github.com/software-mansion/react-native-gesture-handler/issues/139#issuecomment-857474011) issue and replace `componentWillReceiveProps` by React Hooks to support latest React.
