### ISSUE TITLE
Change slider direction

### ISSUE THREAD

**Issue by ertomz** [flyskywhy/react-native-slider-color-picker#3]
Hello! Is there a way to change the direction of the slider color? For example, instead of the SliderValuePicker being darker on the left hand side, can I switch it to be darker on the right hand side?

Thank you!

**Comment by flyskywhy** [comment]
yes

The SliderValuePicker defaultProps of minimumValue and maximumValue is 0.01 and 1, so you just need set them be 1 and 0.01 :stuck_out_tongue: 

ps: in SliderSaturationPicker , you need set a new trackImage to replace the default `saturation_mask.png`

**Comment by ertomz** [comment]
Thank you! I'm actually still having an issue with the values.

When I try setting the max and min value directly I get this error:
`Invariant Violation: inputRange must be monotonically non-decreasing 1,0.02`

Here are the specifications I made:
```
minimumValue={1}
maximumValue={0.02}
```

Even when I try to adjust the step to `step={-0.05}`, this doesn't work.

**Comment by flyskywhy** [comment]
My fault, `darker on the right hand side` can't be simply setting minimumValue and maximumValue.

Cause `darker on the right hand side` mode is not used in most image edit application, so I don't want to modify `react-native-smooth-slider` code which is depended by `react-native-slider-color-picker` or modify `_onColorChange` in `react-native-slider-color-picker/s.js`, thus I suggest you change your code in SliderValuePicker (without customized minimumValue and maximumValue) from

`onColorChange={(colorHsvOrRgb, resType) => {if (resType === 'end') {console.warn(tinycolor(colorHsvOrRgb)).toHexString()}}}`
to
`onColorChange={(colorHsvOrRgb, resType) => {if (resType === 'end') {console.warn(tinycolor({...colorHsvOrRgb, v: 1 - colorHsvOrRgb.v})).toHexString()}}}`
