### ISSUE TITLE
Slider not able to move

### ISSUE THREAD

**Issue by anishappaspect** [flyskywhy/react-native-slider-color-picker#7]
I already set useNativeDriver={true} not able to work in android.

**Comment by flyskywhy** [comment]
What's your Android version of phone, and the `react-native-gesture-handler` version ?

**Comment by anishappaspect** [comment]
> What's your Android version of phone, and the `react-native-gesture-handler` version ?

Android version:-> Android 10,11,12 not working
react-native-gesture-handler: 2.9.0  is latest one 
please replay me as soon as possible

**Comment by anishappaspect** [comment]
> I think your APP miss the `<GestureHandlerRootView />`, please ref to the commit [README.md: descibe some usage of react-native-gesture-handler](https://github.com/flyskywhy/react-native-slider-color-picker/commit/7735154) I just added in `react-native-slider-color-picker@2.2.5`

i added <GestureHandlerRootView /> and update "react-native-smooth-slider": "1.3.9"
now working fine.

Thank you @flyskywhy
